// src/models/arch-nodes.data.js

// ─────────────────────────────────────────────────────────
// CUMPLEAÑOS AMIGA
// ─────────────────────────────────────────────────────────
export const ARCH_CUMPLEANOS = {
  nodes: [
    {
      id: "g-user",
      type: "group",
      position: { x: 20, y: 120 },
      style: { width: 180, height: 140 },
      data: { label: "Actor", color: "#94a3b8" },
    },
    {
      id: "user",
      type: "arch",
      position: { x: 15, y: 35 },
      parentNode: "g-user",
      extent: "parent",
      data: {
        nodeType: "user",
        icon: "👤",
        label: "Visitante",
        tech: "Navegador web",
        desc: "Abre el link sorpresa",
        how: "El usuario recibe un link directo a /software/cumpleanos-amiga/app. Al abrir, React Router carga el componente de forma lazy.",
        why: "No requiere login ni instalación — una URL es suficiente para una sorpresa.",
      },
    },
    {
      id: "g-vercel",
      type: "group",
      position: { x: 260, y: 40 },
      style: { width: 500, height: 340 },
      data: { label: "Portafolio · Vercel", color: "#38bdf8", icon: "▲" },
    },
    {
      id: "router",
      type: "arch",
      position: { x: 30, y: 60 },
      parentNode: "g-vercel",
      extent: "parent",
      data: {
        nodeType: "frontend",
        icon: "🔀",
        label: "React Router",
        tech: "react-router-dom v6",
        desc: "Enruta a /software/:id/app",
        how: "Intercepta la URL y renderiza el componente correcto sin recargar la página. Usa rutas dinámicas con parámetro :id.",
        why: "SPA sin recarga — navegación instantánea.",
        details: [
          "Ruta: /software/cumpleanos-amiga/app",
          "Lazy import del componente",
          "Suspense con PageLoader de fallback",
        ],
      },
    },
    {
      id: "lazy",
      type: "arch",
      position: { x: 280, y: 60 },
      parentNode: "g-vercel",
      extent: "parent",
      data: {
        nodeType: "infra",
        icon: "⚡",
        label: "Lazy Loading",
        tech: "React.lazy + Suspense",
        desc: "Carga solo al navegar",
        how: "React.lazy() envuelve el import dinámico. El bundle de la app solo se descarga cuando el usuario navega a esa ruta.",
        why: "Reduce el bundle inicial del portafolio de ~2MB a ~200KB.",
        details: [
          "Code splitting automático por ruta",
          "Fallback: spinner animado",
          "Prefetch opcional con <Link>",
        ],
      },
    },
    {
      id: "app",
      type: "arch",
      position: { x: 30, y: 210 },
      parentNode: "g-vercel",
      extent: "parent",
      data: {
        nodeType: "frontend",
        icon: "🎂",
        label: "CumpleañosAmiga",
        tech: "React + CSS puro",
        desc: "Carta · Momentos · Regalo",
        how: "Tres secciones con scroll snap: Carta animada con confetti, galería de momentos, y caja de regalo interactiva con confetti.",
        why: "Máximo impacto emocional con tecnología mínima — sin librerías externas.",
        details: [
          "Confetti con canvas API",
          "Animaciones CSS keyframes",
          "Scroll snap CSS nativo",
          "Responsive desde 320px",
        ],
      },
    },
    {
      id: "lexer",
      type: "arch",
      position: { x: 280, y: 210 },
      parentNode: "g-vercel",
      extent: "parent",
      data: {
        nodeType: "compiler",
        icon: "🔤",
        label: "Analizador Léxico",
        tech: "JS puro — sin librerías",
        desc: "Tokeniza el input del usuario",
        how: "Implementado manualmente con autómata finito. Tokeniza caracteres del input y clasifica: amiga, esposa, amante, amor → respuesta personalizada.",
        why: "Proyecto académico de compiladores aplicado a algo real y divertido.",
        details: [
          "Estados: INICIO → LEYENDO → TOKEN",
          "Tokens: RELACION_TYPE, NOMBRE, DESCONOCIDO",
          "Sin ANTLR — JavaScript puro",
        ],
      },
    },
    {
      id: "cdn",
      type: "arch",
      position: { x: 840, y: 160 },
      data: {
        nodeType: "infra",
        icon: "🌐",
        label: "Cloudflare CDN",
        tech: "Edge Network global",
        desc: "Assets estáticos cacheados",
        how: "Vercel usa Cloudflare como CDN. Los assets (JS, CSS, imágenes) se cachean en edge servers cerca del usuario.",
        why: "Latencia < 50ms desde cualquier parte del mundo.",
        details: [
          "Cache-Control: max-age=31536000",
          "Brotli compression",
          "HTTP/3 habilitado",
        ],
      },
    },
  ],
  edges: [
    {
      id: "e1",
      source: "user",
      target: "router",
      animated: true,
      data: { label: "navega" },
      color: "#38bdf8",
    },
    {
      id: "e2",
      source: "router",
      target: "lazy",
      animated: false,
      data: { label: "import()" },
      color: "#a78bfa",
    },
    {
      id: "e3",
      source: "lazy",
      target: "app",
      animated: true,
      data: { label: "renderiza" },
      color: "#38bdf8",
    },
    {
      id: "e4",
      source: "app",
      target: "lexer",
      animated: false,
      data: { label: "input usuario" },
      color: "#e879f9",
    },
    {
      id: "e5",
      source: "router",
      target: "cdn",
      animated: false,
      data: { label: "static assets" },
      color: "#22d3ee",
    },
  ],
};

// ─────────────────────────────────────────────────────────
// ANALIZADOR QUÍMICA — Fullstack + CI/CD
// ─────────────────────────────────────────────────────────
export const ARCH_QUIMICA = {
  nodes: [
    // ── Actor ──
    {
      id: "g-user",
      type: "group",
      position: { x: 20, y: 140 },
      style: { width: 180, height: 140 },
      data: { label: "Actor", color: "#94a3b8" },
    },
    {
      id: "user",
      type: "arch",
      position: { x: 15, y: 35 },
      parentNode: "g-user",
      extent: "parent",
      data: {
        nodeType: "user",
        icon: "🧑‍🎓",
        label: "Estudiante",
        tech: "Navegador",
        desc: "Ingresa fórmula química",
        how: "Escribe una fórmula (ej: Ca3(PO4)2) en el campo de texto del micro-frontend y presiona Analizar.",
        why: "Target principal: estudiantes de química en Guatemala sin acceso a herramientas similares en español con explicación paso a paso.",
      },
    },

    // ── Frontend (Vercel) ──
    {
      id: "g-front",
      type: "group",
      position: { x: 260, y: 60 },
      style: { width: 200, height: 340 },
      data: { label: "Portafolio · Vercel", color: "#38bdf8", icon: "▲" },
    },
    {
      id: "react",
      type: "arch",
      position: { x: 20, y: 50 },
      parentNode: "g-front",
      extent: "parent",
      data: {
        nodeType: "frontend",
        icon: "⚛️",
        label: "React",
        tech: "Vite + CSS Modules",
        desc: "Micro-frontend del analizador",
        how: "Componente lazy-loaded integrado al portafolio. Maneja el formulario de fórmulas, muestra resultados IUPAC/Stock/Tradicional y el quiz interactivo.",
        why: "Reutiliza la infraestructura del portafolio sin servidor frontend propio.",
        details: [
          "useState para form y resultados",
          "useEffect para llamadas a la API",
          "Error boundary para fallos de API",
          "Lazy import con React.lazy()",
        ],
      },
    },
    {
      id: "fetch",
      type: "arch",
      position: { x: 20, y: 215 },
      parentNode: "g-front",
      extent: "parent",
      data: {
        nodeType: "frontend",
        icon: "📡",
        label: "fetch()",
        tech: "REST · JSON",
        desc: "Llama a la API en Koyeb",
        how: "fetch() nativo. POST /api/analizar con { formula } como body. Lee VITE_API_URL del .env para apuntar al endpoint correcto en Koyeb.",
        why: "Sin axios — fetch nativo es suficiente. VITE_API_URL permite cambiar el backend sin tocar el código.",
        details: [
          "POST /api/analizar { formula: string }",
          "AbortController para timeout",
          "CORS manejado por WebConfig.java en el backend",
        ],
      },
    },

    // ── Backend Koyeb — Arquitectura en Capas ──
    {
      id: "g-back",
      type: "group",
      position: { x: 530, y: 20 },
      style: { width: 280, height: 500 },
      data: { label: "Spring Boot · Koyeb", color: "#4ade80", icon: "☁️" },
    },

    {
      id: "controller",
      type: "arch",
      position: { x: 40, y: 50 },
      parentNode: "g-back",
      extent: "parent",
      data: {
        nodeType: "backend",
        icon: "🎮",
        label: "Controller Layer",
        tech: "Spring @RestController",
        desc: "Capa de presentación REST",
        how: "QuimicaController expone los endpoints. @CrossOrigin via WebConfig.java permite requests desde Vercel. Delega toda la lógica al Service.",
        why: "Layered Architecture: la capa Controller solo recibe HTTP y delega — sin lógica de negocio aquí.",
        details: [
          "POST /api/analizar",
          "POST /api/validar",
          "GET /api/quiz",
          "WebConfig.java configura CORS",
        ],
      },
    },
    {
      id: "service",
      type: "arch",
      position: { x: 40, y: 185 },
      parentNode: "g-back",
      extent: "parent",
      data: {
        nodeType: "backend",
        icon: "⚙️",
        label: "Service Layer",
        tech: "NomenclaturService.java",
        desc: "Lógica de negocio — nomenclatura",
        how: "Recibe el Map<String,Integer> de átomos del Visitor, clasifica el tipo de compuesto y aplica el algoritmo correcto para generar IUPAC, Stock y Tradicional con pasos.",
        why: "Separación de capas — el Service no sabe nada de HTTP ni de ANTLR, solo de nomenclatura química.",
        details: [
          "classify() → tipo: óxido, ácido, sal...",
          "toIUPAC(), toStock(), toTradicional()",
          "ElementosDB con 118 elementos",
          "Retorna List<String> de pasos de razonamiento",
        ],
      },
    },
    {
      id: "visitor",
      type: "arch",
      position: { x: 40, y: 320 },
      parentNode: "g-back",
      extent: "parent",
      data: {
        nodeType: "compiler",
        icon: "🌳",
        label: "Visitor Layer",
        tech: "ANTLR4 + FormulaVisitor",
        desc: "Parseo + recorrido del árbol",
        how: "QuimicaLexer tokeniza. QuimicaParser construye el árbol sintáctico. FormulaVisitor extiende QuimicaBaseVisitor y recorre el árbol extrayendo Map<átomo, cantidad>. Maneja grupos con paréntesis anidados.",
        why: "Visitor Pattern: separa el recorrido del árbol (FormulaVisitor) de la gramática (ANTLR). Agregar soporte a nuevos elementos solo requiere editar el .g4.",
        details: [
          "QuimicaLexer.g4 + QuimicaParser.g4",
          "FormulaVisitor extends QuimicaBaseVisitor",
          "Maneja: Ca3(PO4)2 → {Ca:3, P:2, O:8}",
          "Patrón Visitor aplicado sobre árbol ANTLR",
        ],
      },
    },

    // ── CI/CD ──
    {
      id: "g-cicd",
      type: "group",
      position: { x: 890, y: 60 },
      style: { width: 200, height: 360 },
      data: { label: "CI/CD Pipeline", color: "#fb923c", icon: "⚙️" },
    },
    {
      id: "gha",
      type: "arch",
      position: { x: 20, y: 50 },
      parentNode: "g-cicd",
      extent: "parent",
      data: {
        nodeType: "cicd",
        icon: "🐙",
        label: "GitHub Actions",
        tech: "Push → build → push",
        desc: "Trigger: push a main",
        how: "En cada push: checkout → mvn package → docker build → docker push a Docker Hub. El workflow tarda ~3 minutos.",
        why: "Deploy automático — sin intervención manual en cada cambio de gramática.",
        details: [
          "Trigger: push a main branch",
          "mvn package -DskipTests",
          "docker build -t mau-noj/quimica .",
          "docker push → Docker Hub",
        ],
      },
    },
    {
      id: "docker",
      type: "arch",
      position: { x: 20, y: 230 },
      parentNode: "g-cicd",
      extent: "parent",
      data: {
        nodeType: "infra",
        icon: "🐳",
        label: "Docker Hub → Koyeb",
        tech: "Image registry + PaaS",
        desc: "mau-noj/quimica:latest",
        how: "Docker Hub almacena la imagen. Koyeb hace pull automático al detectar nueva imagen. Free tier con spin-down por inactividad (cold start ~10s).",
        why: "Koyeb free tier en Washington DC — latencia aceptable desde Guatemala.",
        details: [
          "Imagen: eclipse-temurin:21-jre-alpine",
          "URL: close-sapphire-mauricionoj-10f63b1b.koyeb.app",
          "Free tier: 0 of 1 running en idle",
          "Cold start: ~10 segundos",
        ],
      },
    },
  ],
  edges: [
    {
      id: "e1",
      source: "user",
      target: "react",
      animated: true,
      data: { label: "formula input" },
      color: "#38bdf8",
    },
    {
      id: "e2",
      source: "react",
      target: "fetch",
      animated: false,
      data: { label: "llama" },
      color: "#38bdf8",
    },
    {
      id: "e3",
      source: "fetch",
      target: "controller",
      animated: true,
      data: { label: "POST /api/analizar" },
      color: "#4ade80",
    },
    {
      id: "e4",
      source: "controller",
      target: "service",
      animated: false,
      data: { label: "delega" },
      color: "#4ade80",
    },
    {
      id: "e5",
      source: "service",
      target: "visitor",
      animated: false,
      data: { label: "parsea fórmula" },
      color: "#e879f9",
    },
    {
      id: "e6",
      source: "visitor",
      target: "service",
      animated: false,
      data: { label: "Map<átomo,n>" },
      color: "#e879f9",
    },
    {
      id: "e7",
      source: "service",
      target: "controller",
      animated: false,
      data: { label: "ResultadoAnalisis" },
      color: "#4ade80",
    },
    {
      id: "e8",
      source: "controller",
      target: "fetch",
      animated: true,
      data: { label: "JSON response" },
      color: "#4ade80",
    },
    {
      id: "e9",
      source: "gha",
      target: "docker",
      animated: true,
      data: { label: "push image" },
      color: "#fb923c",
    },
    {
      id: "e10",
      source: "docker",
      target: "controller",
      animated: false,
      data: { label: "deploy en Koyeb" },
      color: "#a78bfa",
    },
  ],
};

export const ARCH_LABORATORIO = {
  nodes: [
    {
      id: "g-actors",
      type: "group",
      position: { x: 20, y: 60 },
      style: { width: 180, height: 320 },
      data: { label: "Actores", color: "#94a3b8" },
    },
    {
      id: "admin",
      type: "arch",
      position: { x: 15, y: 40 },
      parentNode: "g-actors",
      extent: "parent",
      data: {
        nodeType: "user",
        icon: "👨‍💼",
        label: "Administrador",
        tech: "Navegador",
        desc: "Gestión total del sistema",
        how: "Accede al dashboard con credenciales propias. Puede gestionar usuarios, ver todos los reportes y configurar el sistema.",
        why: "Separación de responsabilidades por rol — el admin ve todo, el docente solo sus prácticas.",
      },
    },
    {
      id: "docente",
      type: "arch",
      position: { x: 15, y: 185 },
      parentNode: "g-actors",
      extent: "parent",
      data: {
        nodeType: "user",
        icon: "👨‍🏫",
        label: "Docente",
        tech: "Navegador",
        desc: "Prácticas y asistencia",
        how: "Crea y gestiona sus propias prácticas, registra asistencia por sesión y genera reportes PDF de sus grupos.",
        why: "El docente es el usuario principal del sistema — su flujo de trabajo fue el que se documentó con RUP.",
      },
    },

    {
      id: "g-front",
      type: "group",
      position: { x: 265, y: 30 },
      style: { width: 200, height: 400 },
      data: { label: "Frontend · Vercel", color: "#38bdf8", icon: "▲" },
    },
    {
      id: "react",
      type: "arch",
      position: { x: 20, y: 50 },
      parentNode: "g-front",
      extent: "parent",
      data: {
        nodeType: "frontend",
        icon: "⚛️",
        label: "React SPA",
        tech: "Vite + CSS Modules",
        desc: "Dashboard · Prácticas · Equipos",
        how: "SPA con rutas protegidas. Verifica el JWT antes de renderizar cualquier ruta privada. Layout con sidebar para navegación entre módulos.",
        why: "SPA evita recargas — la experiencia del docente registrando asistencia es fluida.",
        details: [
          "React Router v6 con rutas protegidas",
          "Context API para estado de sesión",
          "CSS Modules por componente",
          "Vite HMR en desarrollo",
        ],
      },
    },
    {
      id: "jwt-c",
      type: "arch",
      position: { x: 20, y: 240 },
      parentNode: "g-front",
      extent: "parent",
      data: {
        nodeType: "auth",
        icon: "🔐",
        label: "JWT Client",
        tech: "localStorage",
        desc: "Adjunta Bearer en cada request",
        how: "Al login exitoso, el token JWT se guarda en localStorage. Un interceptor lo adjunta en el header Authorization: Bearer <token> en cada fetch.",
        why: "Stateless auth — el servidor no guarda sesiones. Escala bien.",
        details: [
          'localStorage.setItem("token", jwt)',
          "Authorization: Bearer ${token}",
          "Expiración: 8 horas",
          "Refresh manual al expirar",
        ],
      },
    },

    {
      id: "g-back",
      type: "group",
      position: { x: 535, y: 20 },
      style: { width: 220, height: 440 },
      data: { label: "Backend · Dokploy", color: "#4ade80", icon: "🖥️" },
    },
    {
      id: "express",
      type: "arch",
      position: { x: 25, y: 50 },
      parentNode: "g-back",
      extent: "parent",
      data: {
        nodeType: "backend",
        icon: "🟢",
        label: "Express API",
        tech: "Node.js · REST",
        desc: "Controllers · Middleware · Routes",
        how: "API REST con rutas agrupadas por módulo: /auth, /practicas, /equipos, /asistencia, /reportes. Cada ruta pasa por middleware de autenticación.",
        why: "Express es minimalista — estructura clara sin magia. Fácil de mantener por un solo desarrollador.",
        details: [
          "express.Router() por módulo",
          "Middleware: authMiddleware, roleCheck",
          "mysql2 con connection pool",
          "multer para upload de fotos",
        ],
      },
    },
    {
      id: "jwt-s",
      type: "arch",
      position: { x: 25, y: 200 },
      parentNode: "g-back",
      extent: "parent",
      data: {
        nodeType: "auth",
        icon: "🛡️",
        label: "JWT + Bcrypt",
        tech: "jsonwebtoken + bcrypt",
        desc: "Verifica roles en cada request",
        how: "authMiddleware verifica la firma del JWT en cada request protegido. roleCheck valida que el rol del usuario permita la operación.",
        why: "OWASP Top 10: autenticación robusta sin sesiones server-side.",
        details: [
          "jwt.verify(token, process.env.JWT_SECRET)",
          "bcrypt.compare() en login",
          "Roles: admin, docente, estudiante",
          "Payload JWT: { userId, rol, iat, exp }",
        ],
      },
    },
    {
      id: "pdf",
      type: "arch",
      position: { x: 25, y: 340 },
      parentNode: "g-back",
      extent: "parent",
      data: {
        nodeType: "backend",
        icon: "📄",
        label: "PDF Service",
        tech: "pdfkit",
        desc: "Genera reportes de asistencia",
        how: "Consulta MySQL, genera el PDF en memoria con pdfkit y lo sube a Cloudflare R2. Devuelve la URL pública al frontend.",
        why: "Reportes PDF es el requerimiento más importante para los docentes.",
        details: [
          "pdfkit para generación en memoria",
          "Buffer stream → R2 upload",
          "URL firmada con 7 días de expiración",
          "Plantillas: asistencia, inventario equipos",
        ],
      },
    },

    {
      id: "g-data",
      type: "group",
      position: { x: 835, y: 40 },
      style: { width: 200, height: 400 },
      data: { label: "Persistencia", color: "#f59e0b", icon: "🗄️" },
    },
    {
      id: "mysql",
      type: "arch",
      position: { x: 20, y: 50 },
      parentNode: "g-data",
      extent: "parent",
      data: {
        nodeType: "database",
        icon: "🐬",
        label: "MySQL 8",
        tech: "Dokploy · mismo host",
        desc: "Prácticas · Equipos · Usuarios",
        how: "Base de datos relacional en el mismo servidor que Express. Connection pool de 10 conexiones. Tablas: usuarios, practicas, equipos, asistencia, grupos.",
        why: "Datos relacionales con integridad referencial — una práctica tiene múltiples grupos, cada grupo tiene múltiples estudiantes.",
        details: [
          "5 tablas principales",
          "Connection pool: min 2, max 10",
          "Charset: utf8mb4",
          "Backups automáticos Dokploy: diarios",
        ],
      },
    },
    {
      id: "r2",
      type: "arch",
      position: { x: 20, y: 240 },
      parentNode: "g-data",
      extent: "parent",
      data: {
        nodeType: "storage",
        icon: "☁️",
        label: "Cloudflare R2",
        tech: "S3-compatible API",
        desc: "Fotos de equipos · PDFs generados",
        how: "Compatible con el SDK de AWS S3. El backend usa @aws-sdk/client-s3 apuntando al endpoint de R2. Sin egress fees.",
        why: "R2 es gratuito hasta 10GB y sin costo de egress — perfecto para un sistema académico.",
        details: [
          "Bucket: laboratorio-assets",
          "Sin egress fees (vs S3)",
          "@aws-sdk/client-s3 compatible",
          "URLs firmadas para descargas privadas",
        ],
      },
    },
  ],
  edges: [
    {
      id: "e1",
      source: "admin",
      target: "react",
      animated: true,
      data: { label: "usa" },
      color: "#38bdf8",
    },
    {
      id: "e2",
      source: "docente",
      target: "react",
      animated: true,
      data: { label: "usa" },
      color: "#38bdf8",
    },
    {
      id: "e3",
      source: "react",
      target: "jwt-c",
      animated: false,
      data: { label: "adjunta token" },
      color: "#f43f5e",
    },
    {
      id: "e4",
      source: "jwt-c",
      target: "express",
      animated: true,
      data: { label: "fetch + Bearer" },
      color: "#4ade80",
    },
    {
      id: "e5",
      source: "express",
      target: "jwt-s",
      animated: false,
      data: { label: "verifica rol" },
      color: "#f43f5e",
    },
    {
      id: "e6",
      source: "express",
      target: "mysql",
      animated: true,
      data: { label: "queries SQL" },
      color: "#f59e0b",
    },
    {
      id: "e7",
      source: "express",
      target: "pdf",
      animated: false,
      data: { label: "genera reporte" },
      color: "#4ade80",
    },
    {
      id: "e8",
      source: "pdf",
      target: "r2",
      animated: false,
      data: { label: "sube PDF" },
      color: "#22d3ee",
    },
    {
      id: "e9",
      source: "express",
      target: "react",
      animated: true,
      data: { label: "JSON response" },
      color: "#4ade80",
    },
  ],
};
